// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJkpk48W3IzzxpNJGXqW1aTmRTQJdLcE',
    appId: '1:920562730238:android:f8cb3f846958a80a2b11af',
    messagingSenderId: '920562730238',
    projectId: 'flutter-firebase-test-ap-f11c1',
    storageBucket: 'flutter-firebase-test-ap-f11c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGgWMbBaJ480Aj5U1oQWvHuAFUGYkt5g',
    appId: '1:920562730238:ios:22436066bd7f7b172b11af',
    messagingSenderId: '920562730238',
    projectId: 'flutter-firebase-test-ap-f11c1',
    storageBucket: 'flutter-firebase-test-ap-f11c1.appspot.com',
    iosClientId: '920562730238-mq5cvf6of9duv8jv99mpjc007dtmle82.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );
}
